execute: compile
	./guiao_1 /Users/ricardopetronilho/Desktop/SO/file.txt 

compile: clear
	gcc -Wall guiao_1.c -o guiao_1

clear: 
	clear

clean: 
	rm hello.txt file.txt file2.txt guiao_1 helloWorld.txt arrayA.txt

git -i: git_commit
	git push origin master

git_commit: git_add
	git commit -m "auto-commit"

git_add: 
	git add *





